name: C/C++ Static Code Analysis

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: install cppcheck
      run: sudo apt -y install cppcheck
    - name: Static Code analysis
      run: make -C 3_Implementation/ cppcheck

