name: C/C++ dynamic Code Analysis

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Valgrind
      run: sudo apt -y install valgrind
    - name: dynamic code analysis
      run: make 3_Implementation/ valgrind

